
/**
 * Enumeration class State represents all available states
 * 
 * @author (your name here)
 * @version (version number or date here)
 */
public enum State
{
    //INITIAL STATES
    INITIAL, LOGIN, REGISTER,
    
    //CLERK STATES
    CLERKSTART, PROCESSRETURN, RETURNITEMS, RETURNCONFIRM,
    
    //MANAGER STATES
    MGRSTART, ADDITEMS, PROCDELIVERY, DSRINIT, DSRSUCCESS, DSRFAILURE,
    NTSRINIT, NTSRSUCCESS, NTSRFAILURE,
    
    //CUSTOMER METHODS
    CUSTSTART, SEARCHSTATE, SELECTITEM, CHECKQTY, INSFSTOCK, SEARCHFAILED, 
    ADDTOVSB, VIEWVSB, CLEARVSB, PLACEORDER, CHECKQTYFINAL, PAYFORORDER,
    ORDERFINAL, RECEIPT, ORDERFAIL,
    
    //OTHER STATES
    EXIT
    
}
